flags: {}
extra-package-dbs: []
packages:
    - .
extra-deps:
- hjpath-3.0.1
- hjson-1.3.2
- ref-tf-0.4.0.1
- git: https://github.com/reflex-frp/reflex.git
  commit: 4a03273794aa4c9a9965e3e6a45fa3c68fa4659a
- git: https://github.com/bennofs/reflex-host.git
  commit: ab72c16077ab3bcc1c1e81312aac1090e64b97d4
- prim-uniq-0.1.0.1
resolver: nightly-2017-11-17
