flags: {}
extra-package-dbs: []
packages:
    - location: .
    - location: /home/xandaros/workspace/reflex
      extra-dep: true
    - location: /home/xandaros/workspace/reflex-host
      extra-dep: true
extra-deps:
- hjpath-3.0.1
- hjson-1.3.2
- ref-tf-0.4.0.1
- reflex-0.5.0
- reflex-host-0.3
- prim-uniq-0.1.0.1
resolver: nightly-2017-11-17
